version: '3.8'
services:
  app:
    build: .
    ports:
    - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - db
  db:
    image: 'mysql:latest'
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pato' 
    volumes:
      - jorgeltest-data:/foo
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - mynetwork
volumes:
  jorgeltest-data:
networks:
  mynetwork: